version: '3.1'

services:
  api: 
    container_name: golang-crud
    build: 
      context: .
      target: dev
    env_file:
      - ./pkg/common/envs/.env
    depends_on:
      - db
    links: 
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: g0l4ng
      POSTGRES_DB: golang-crud
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: